import * as assert from "assert";
import { describe, it } from "node:test";
import {
  buildAiFailureContext,
  formatRunTargetScopeLabels,
  LastRunSnapshot,
  tailOutputLines,
} from "../core/diagnostics/aiFailureContext";
import { FeatureInfo, OutlineExample, ScenarioInfo } from "../core/gherkin/model";
import { RunTarget } from "../core/runner/filterBuilder";

function baseSnapshot(overrides: Partial<LastRunSnapshot> = {}): LastRunSnapshot {
  return {
    timestamp: Date.parse("2026-05-30T12:00:00.000Z"),
    stage: "test",
    mode: "parallel",
    filter: "Category=smoke",
    scopeLabels: ["@smoke (tag)"],
    projectDir: "/repo/samples/minimal-bdd",
    exitCode: 1,
    summary: { passed: 5, failed: 2, skipped: 0, total: 7, source: "trx" },
    outputForAnalysis: "line1\nline2\nFailed!  - Failed: 2, Passed: 5, Skipped: 0, Total: 7",
    failedScenarios: [
      {
        featurePath: "/repo/samples/minimal-bdd/Features/Login.feature",
        scenarioName: "User can log in",
        errorMessage: "Expected true but was false",
      },
    ],
    evidence: [],
    ...overrides,
  };
}

describe("aiFailureContext", () => {
  it("builds markdown with Run, Failed scenarios, and footer sections", () => {
    const md = buildAiFailureContext(baseSnapshot(), { extensionVersion: "0.4.0" });
    assert.match(md, /^# BDD Pilot — failure context/m);
    assert.match(md, /## Run/);
    assert.match(md, /\*\*Stage:\*\* test · \*\*Mode:\*\* parallel/);
    assert.match(md, /`Category=smoke`/);
    assert.match(md, /## Failed scenarios/);
    assert.match(md, /`Login\.feature` · User can log in/);
    assert.match(md, /Generated by BDD Pilot v0\.4\.0/);
  });

  it("lists failed scenarios with truncated error snippets", () => {
    const longErr = "x".repeat(200);
    const md = buildAiFailureContext(
      baseSnapshot({
        failedScenarios: [
          {
            featurePath: "/repo/F.feature",
            scenarioName: "S",
            errorMessage: longErr,
          },
        ],
      }),
    );
    assert.match(md, /S — _x+/);
    assert.ok(!md.includes(longErr));
  });

  it("includes diagnostics block when analyzer matches output", () => {
    const out = [
      "Test run for /repo/bin/Debug/net8.0/App.dll",
      "No test matches the given testcase filter `FullyQualifiedName~Nope` in X.dll",
    ].join("\n");
    const md = buildAiFailureContext(baseSnapshot({ outputForAnalysis: out }));
    assert.match(md, /## Diagnostics \(BDD Pilot analyzer\)/);
    assert.match(md, /\[NO_TESTS_MATCHED\]/);
  });

  it("shows fallback diagnostics message when output has no rule match", () => {
    const md = buildAiFailureContext(
      baseSnapshot({ outputForAnalysis: "Passed!  - Failed: 0, Passed: 10, Skipped: 0, Total: 10" }),
    );
    assert.match(md, /No rule matched — see output below/);
  });

  it("caps output tail to maxOutputLines", () => {
    const lines = Array.from({ length: 30 }, (_, i) => `line-${i + 1}`).join("\n");
    const md = buildAiFailureContext(baseSnapshot({ outputForAnalysis: lines }), {
      maxOutputLines: 5,
    });
    assert.match(md, /last 5 lines/);
    assert.match(md, /line-26/);
    assert.match(md, /line-30/);
    assert.ok(!md.includes("line-24"));
  });

  it("redacts secrets in the output section", () => {
    const md = buildAiFailureContext(
      baseSnapshot({
        outputForAnalysis: "password=super-secret-token\nFailed!  - Failed: 1, Passed: 0, Skipped: 0, Total: 1",
      }),
      { maxOutputLines: 10 },
    );
    assert.match(md, /password=\*\*\*REDACTED\*\*\*/);
    assert.ok(!md.includes("super-secret-token"));
  });

  it("formats tag and scenario scope labels", () => {
    const feature: FeatureInfo = {
      name: "Login",
      filePath: "/repo/Features/Login.feature",
      tags: [],
      scenarios: [],
    };
    const scenario: ScenarioInfo = {
      name: "User logs in",
      tags: [],
      line: 5,
      isOutline: false,
    };
    const example: OutlineExample = {
      rowIndex: 0,
      line: 12,
      headers: ["id"],
      values: ["1"],
      label: "id=1",
    };
    const targets: RunTarget[] = [
      { kind: "tag", tag: "smoke" },
      { kind: "scenario", feature, scenario },
      { kind: "outlineRow", feature, scenario, example },
    ];
    assert.deepStrictEqual(formatRunTargetScopeLabels(targets), [
      "@smoke (tag)",
      "Login.feature · User logs in (scenario)",
      "Login.feature · User logs in — id=1 (outline row)",
    ]);
  });

  it("tailOutputLines returns last N lines", () => {
    const text = "a\nb\nc\nd\ne";
    assert.strictEqual(tailOutputLines(text, 2), "d\ne");
    assert.strictEqual(tailOutputLines(text, 10), text);
  });
});
